-- PRXDIGY staff portal schema
-- Run this in the Supabase SQL editor before loading the private menu seed.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  full_name text not null default '',
  role text not null default 'staff' check (role in ('admin', 'sales', 'studio', 'creative', 'staff')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text not null default '';

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  division text not null check (division in ('studio', 'creative')),
  location text not null default 'all' check (location in ('all', 'brooklyn', 'long_island')),
  audience text not null,
  category text not null,
  name text not null,
  price_label text not null,
  description text not null default '',
  best_for text not null default '',
  recommend_when text not null default '',
  next_offer text not null default '',
  terms text not null default '',
  package_items text[] not null default '{}',
  badge text not null default '',
  requires_confirmation boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.portal_notes (
  id bigint generated by default as identity primary key,
  section text not null,
  title text not null,
  body text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at
before update on public.services
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_approved_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and status = 'approved'
  );
$$;

create or replace function public.is_portal_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and status = 'approved' and role = 'admin'
  );
$$;

create or replace function public.admin_set_member_status(
  target_user uuid,
  next_status text,
  next_role text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_portal_admin() then
    raise exception 'Admin access required';
  end if;

  if next_status not in ('pending', 'approved', 'rejected') then
    raise exception 'Invalid status';
  end if;

  if next_role not in ('admin', 'sales', 'studio', 'creative', 'staff') then
    raise exception 'Invalid role';
  end if;

  update public.profiles
  set status = next_status, role = next_role
  where id = target_user;
end;
$$;

revoke all on function public.admin_set_member_status(uuid, text, text) from public;
grant execute on function public.admin_set_member_status(uuid, text, text) to authenticated;

alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.portal_notes enable row level security;

drop policy if exists "Members read own profile" on public.profiles;
create policy "Members read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "Admins read all profiles" on public.profiles;
create policy "Admins read all profiles"
on public.profiles for select
to authenticated
using (public.is_portal_admin());

drop policy if exists "Approved staff read services" on public.services;
create policy "Approved staff read services"
on public.services for select
to authenticated
using (public.is_approved_staff() and is_active = true);

drop policy if exists "Admins manage services" on public.services;
create policy "Admins manage services"
on public.services for all
to authenticated
using (public.is_portal_admin())
with check (public.is_portal_admin());

drop policy if exists "Approved staff read notes" on public.portal_notes;
create policy "Approved staff read notes"
on public.portal_notes for select
to authenticated
using (public.is_approved_staff() and is_active = true);

drop policy if exists "Admins manage notes" on public.portal_notes;
create policy "Admins manage notes"
on public.portal_notes for all
to authenticated
using (public.is_portal_admin())
with check (public.is_portal_admin());

grant select on public.profiles to authenticated;
grant select on public.services to authenticated;
grant select on public.portal_notes to authenticated;
grant insert, update, delete on public.services to authenticated;
grant insert, update, delete on public.portal_notes to authenticated;

-- After the owner creates an account, bootstrap exactly one admin in the SQL editor:
-- update public.profiles set status = 'approved', role = 'admin'
-- where id = (select id from auth.users where email = 'OWNER_EMAIL_HERE');
